services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: sentinel
      POSTGRES_PASSWORD: sentinel
      POSTGRES_DB: sentinel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://sentinel:sentinel@db:5432/sentinel
      MODEL_PATH: models/fraud_model.joblib
      MLFLOW_TRACKING_URI: http://mlflow:5000
    depends_on:
      - db
      - mlflow
    volumes:
      - ./models:/app/models
      - bentoml_store:/home/bentoml

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow/mlflow.db --default-artifact-root /mlflow/artifacts
    ports:
      - "5000:5000"
    volumes:
      - mlflow_data:/mlflow

volumes:
  pgdata:
  mlflow_data:
  bentoml_store:
